backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Locations"
    name: "locations"
    files:
      - label: "Nottingham"
        name: "nottingham"
        file: "content/locations/nottingham.md"
        fields:
          - { label: Title, name: title, widget: string, required: true }
          - { label: Description, name: description, widget: text, required: true }
          - { label: Location, name: location, widget: text, required: true }
          - { label: Phone Number, name: phone, widget: number, required: true }
          - { label: Content, name: body, widget: markdown }
